# Default values for monipywdd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: thawngv/ddpy-flask-alpha
  pullPolicy: Always
  tag: "latest"

# Application log
path_to_log_dir: /var/log/flashblog
path_to_log_file: /var/log/flashblog/flashblog.log
config_map_name: applog-config

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 5000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}
